### ISSUE TITLE
/join sometimes results in no confirmation nor messages from MUC, but JID still joins room

### ISSUE THREAD

**Issue by ossguy** [singpolyma/cheogram#29]
In some situations (such as after my JID is kicked from a room, or occasionally when Cheogram itself is restarted) and when /who is giving me "You are joined to  as <nickname> along with", when I then do "/join <MUC>" I get no response from Cheogram (such as the usual "you have joined" message) and I get no messages from the MUC delivered to me.  However, my JID does join the MUC - it's just that I can't see anything happening there.

If I then do "/join <MUC>" again, I do get the Cheogram greeting and the MUC messages start to be delivered.  The JID that has already joined the MUC remains unchanged (it stays joined to the room).

My usual JID is currently stuck in the state after the first /join in case you wanted to take a look.

This might be related to #2 or possibly to #25.

**Comment by singpolyma** [comment]
Ok, so, on line 209 I am pattern matching assuming there is only one status code, but there can in fact be more than one.  This is almost certainly the bug
