### ISSUE TITLE
No welcome message sent to (some) new users

### ISSUE THREAD

**Issue by ossguy** [singpolyma/cheogram#3]
From the two numbers I tried this morning, I didn't receive a welcome message to either.  If I sent a random non-command, I would get back "You are not joined to a group", which wasn't too helpful.  I understand there is a welcome message that should be sent, but perhaps it's not working in some cases (in both situations, this was a new number that had not been /invite'ed).

In the interim, it might be nice to change 'You are not joined to a group' to 'You are not joined to a group; you can reply with "/help" to get a list of commands'.

**Comment by singpolyma** [comment]
This *seems* to have been delivery failure, which is an unfortunate thing that can happen.  I have added the suggested helpful text.  Will keep an eye on this.
