### ISSUE TITLE
"* <user> has joined the group" repeats a lot for some users, unlike with other XMPP clients

### ISSUE THREAD

**Issue by ossguy** [singpolyma/cheogram#4]
For certain &lt;user&gt;s in certain MUCs, I get "* &lt;user&gt; has joined the group" quite frequently, perhaps after every second message that <user> sends to the group.  Other XMPP clients connected to the same MUC (I've tested Psi in particular) do not display such messages.  Perhaps there is a particular XMPP message type that CheoGram is using to trigger these announcements that is a bit too granular for the purpose?

**Comment by singpolyma** [comment]
Probably I should just not send such messages for anyone who was already in my known list of group participants
