### ISSUE TITLE
Send <presence type="subscribe"/> to users configured by a third party

### ISSUE THREAD

**Issue by singpolyma** [singpolyma/cheogram#58]
Since they have not interacted with cheogram over XMPP yet, they may otherwise have to be told to add `cheogram.com` to their roster (which they need to enable `jabber:iq:gateway` and other such magic).

Since @ossguy will be the first user of this "third party configuration" support, should get his feedback before proceeding with this.

**Comment by ossguy** [comment]
Per our discussion in the discuss@conference.soprani.ca MUC (URI: xmpp:discuss@conference.soprani.ca?join - GitHub refuses to add links to xmpp: URIs) and the "JID Translation" section of https://cheogram.com/xmpp/ , I'm fine with this.  I can always add some text to [jmp-register](https://gitlab.com/ossguy/jmp-register/tree/master) if needed, to prepare the user for this request that they'll be receiving.
